version: '3.7'

services:
  arr-cleaner:
    container_name: arr-cleaner
    image: sivert/arr-cleaner
    build:
      context: .
    environment:
      SONARR_URL: ${SONARR_URL}
      RADARR_URL: ${RADARR_URL}
      SONARR_API_KEY: ${SONARR_API_KEY}
      RADARR_API_KEY: ${RADARR_API_KEY}
      API_TIMEOUT: ${API_TIMEOUT}
    restart: unless-stopped
